# Generated by Django 3.2.16 on 2022-12-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Task1',
        ),
    ]
