# Generated by Django 3.2.16 on 2022-12-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_task_task1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='date',
            field=models.DateField(default='2022-12-28'),
            preserve_default=False,
        ),
    ]
